name: GitHub Pages
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check-out repository
        uses: actions/checkout@v2
      - name: Setup Java JDK
        uses: actions/setup-java@v1.3.0
        with:
          java-version: 1.8
      - name: Download XProc
        run: wget "https://github.com/ndw/xmlcalabash1/releases/download/1.2.1-98/xmlcalabash-1.2.1-98.zip" -q && unzip -q "*.zip" -d "./calabash"
      - name: Download XSpec
        run: wget "https://github.com/xspec/xspec/archive/v1.6.0.zip" -q && unzip -q "*.zip" -d "./xspec"
      - name: Run build
        run: |
          xspec_dir=xspec/xspec-1.6.0/src
          xspec_dir_uri=file:$(pwd)/${xspec_dir}
          java -jar calabash/xmlcalabash-1.2.1-98/xmlcalabash-1.2.1-98.jar --with-param xspec-home="${xspec_dir_uri}" $GITHUB_WORKSPACE/xproc/build.xpl
      - name: Commit result
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git checkout --orphan gh-pages
          git add index.html
          git commit -m "Add page"
      - name: Push result
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          branch: gh-pages
          force: true
